[package]
name = "ffi"
version = "0.1.0"
authors = ["wkcn <wkcn@live.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "ffi"
crate-type = ["dylib"]
